db:
  image: postgres
redis:
  image: redis
web:
  build: .
  command: python manage.py runserver_plus 0.0.0.0:8000
  volumes:
    - .:/code
    #- ../django-report-utils/report_utils:/usr/local/lib/python3.4/site-packages/report_utils
    #- ../django-custom-field/custom_field:/usr/local/lib/python3.4/site-packages/custom_field
  ports:
    - "8000:8000"
  links:
    - db
    - redis
celery:
  build: .
  command: celery -A report_builder_demo worker -l info
  links:
    - db
    - redis
  environment:
    C_FORCE_ROOT: true
  volumes:
    - .:/code
